# Generated by Django 4.0.3 on 2022-06-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='suthor',
            new_name='author',
        ),
    ]
