# Generated by Django 4.0.3 on 2022-06-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='author',
            new_name='recipe',
        ),
    ]
