# Generated by Django 4.0.3 on 2022-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_step_food_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='origin',
            field=models.TextField(null=True),
        ),
    ]
