# Generated by Django 4.0.3 on 2022-06-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
