# Generated by Django 4.0.3 on 2022-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='origin',
        ),
        migrations.AddField(
            model_name='recipe',
            name='origin_new',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
