# Generated by Django 4.0.3 on 2022-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_recipe_origin_recipe_origin_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='origin_new',
        ),
        migrations.AddField(
            model_name='recipe',
            name='origin',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
