# Generated by Django 4.0.3 on 2022-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_remove_recipe_origin_new_recipe_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='origin',
            field=models.IntegerField(null=True),
        ),
    ]
